swiftmailer:
#    url: '%env(MAILER_URL)%'
#    spool: { type: 'memory' }
     transport: gmail
     host: stmp.gmail.com
     port: 465
     encryption: ssl
     username: gaumap228@gmail.com
     password: gaumapnhatnha
